"""
Multibronnen: ketens/families waar 1 parser veel locaties dekt.
De scraper probeert per locatie de padvarianten; wat niet bestaat of
niets zegt, faalt stil. indicator-niveaus: duur > wachtlijst > direct.
"""

# Sportfondsen-module: {sub}.sportfondsen.nl + 2 padvarianten
SF_PADEN = ["/ik-ben-nieuw/wachtlijst/", "/zwemles/ik-ben-nieuw/wachtlijst/",
            "/zwemles/ik-ben-nieuw/", "/zwemles/"]
SPORTFONDSEN = [
 ("sf-oostelijk","Sportfondsen Oostelijk Zwembad","Rotterdam","Zuid-Holland","oostelijkzwembad"),
 ("sf-oostervant","Recreatiecentrum Oostervant","Rotterdam","Zuid-Holland","oostervant"),
 ("sf-vanmaanen","Van Maanenbad","Rotterdam","Zuid-Holland","vanmaanenbad"),
 ("sf-zevenkamp","Sportfondsen Zevenkampse Ring","Rotterdam","Zuid-Holland","zevenkampsering"),
 ("sf-adamoost","Sportfondsenbad Amsterdam-Oost","Amsterdam","Noord-Holland","amsterdamoost"),
 ("sf-mercator","SportPlaza Mercator","Amsterdam","Noord-Holland","mercator"),
 ("sf-wedde","Zwembad Het Wedde","Voorschoten","Zuid-Holland","wedde"),
 ("sf-sterrenbad","Sterrenbad","Wassenaar","Zuid-Holland","sterrenbad"),
 ("sf-hooghewaerd","De Hooghe Waerd","IJsselstein","Utrecht","hooghewaerd"),
 ("sf-beverwijk","Sportfondsenbad Beverwijk","Beverwijk","Noord-Holland","beverwijk"),
 ("sf-monnickendam","Sportfondsenbad Monnickendam","Monnickendam","Noord-Holland","monnickendam"),
 ("sf-gennep","Sportfondsen Gennep","Gennep","Limburg","gennep"),
 ("sf-skwa","Sportcomplex Koning Willem Alexander","Hoofddorp","Noord-Holland","skwa"),
 ("sf-stichtsevecht","Sportfondsen Stichtse Vecht","Maarssen","Utrecht","stichtsevecht"),
]

# Optisport: locatiepagina + zwemlespagina-varianten
OPTI_PADEN = ["", "/zwemles", "/activiteiten/zed-sop-zwemles"]
OPTISPORT = [
 ("opti-walfort","Zwembad 't Walfort","Aalten","Gelderland","https://www.optisport.nl/zwembad-t-walfort-aalten"),
 ("opti-gelenberg","Zwembad De Gelenberg","Druten","Gelderland","https://www.optisport.nl/zwembad-de-gelenberg-druten"),
 ("opti-almerepoort","Zwembad Almere Poort","Almere","Flevoland","https://www.optisport.nl/zwembad-almere-poort"),
 ("opti-almerestad","Zwembad Almere Stad","Almere","Flevoland","https://www.optisport.nl/zwembad-almere-stad"),
 ("opti-vrijbuiter","Zwembad De Vrijbuiter","Almere","Flevoland","https://www.optisport.nl/zwembad-de-vrijbuiter"),
 ("opti-muziekwijk","Zwembad Muziekwijk","Almere","Flevoland","https://www.optisport.nl/zwembad-muziekwijk"),
 ("opti-tussendevaarten","Zwembad Tussen de Vaarten","Almere","Flevoland","https://www.optisport.nl/zwembad-tussen-de-vaarten"),
 ("opti-bijlmer","Zwembad Bijlmer","Amsterdam","Noord-Holland","https://www.optisport.nl/zwembad-bijlmer-amsterdam-zuidoost"),
 ("opti-sloterparkbad","Het Sloterparkbad","Amsterdam","Noord-Holland","https://www.optisport.nl/zwembad-het-sloterparkbad-amsterdam"),
 ("opti-aquaaltena","Zwembad AquaAltena","Andel","Noord-Brabant","https://www.optisport.nl/zwembad-aquaaltena-andel"),
 ("opti-veluwehal","Zwembad De Veluwehal","Barneveld","Gelderland","https://www.optisport.nl/zwembad-de-veluwehal-barneveld"),
 ("opti-hofstee","Zwembad De Hofstee","Bergambacht","Zuid-Holland","https://www.optisport.nl/zwembad-de-hofstee-bergambacht"),
 ("opti-smagtenbocht","Zwembad De Smagtenbocht","Bladel","Noord-Brabant","https://www.optisport.nl/zwembad-de-smagtenbocht-bladel"),
 ("opti-kuil","Zwembad De Kuil","Bodegraven","Zuid-Holland","https://www.optisport.nl/zwembad-de-kuil-bodegraven"),
 ("opti-hoogkoor","Zwembad 't Hoogkoor","Boxmeer","Noord-Brabant","https://www.optisport.nl/zwembad-t-hoogkoor-boxmeer"),
 ("opti-dommelbad","Zwembad Het Dommelbad","Boxtel","Noord-Brabant","https://www.optisport.nl/zwembad-het-dommelbad-boxtel"),
 ("opti-wisselaar","Zwembad De Wisselaar","Breda","Noord-Brabant","https://www.optisport.nl/zwembad-de-wisselaar-breda"),
 ("opti-sonsbeeck","Zwembad Sonsbeeck","Breda","Noord-Brabant","https://www.optisport.nl/zwembad-sonsbeeck-breda"),
 ("opti-waterlinie","Zwembad De Waterlinie","Culemborg","Gelderland","https://www.optisport.nl/zwembad-de-waterlinie-culemborg"),
 ("opti-dalfsen","Zwembad Dalfsen","Dalfsen","Overijssel","https://www.optisport.nl/zwembad-dalfsen"),
 ("opti-vreeloo","Zwembad Vreeloo","De Lier","Zuid-Holland","https://www.optisport.nl/zwembad-vreeloo-de-lier"),
 ("opti-dubbelslag","Zwembad Dubbelslag","Delfzijl","Groningen","https://www.optisport.nl/zwembad-dubbelslag-delfzijl"),
 ("opti-tolhuisbad","Zwembad Tolhuisbad","Dokkum","Friesland","https://www.optisport.nl/zwembad-tolhuisbad-dokkum"),
 ("opti-dordrecht","Zwembad Dordrecht (Sportboulevard)","Dordrecht","Zuid-Holland","https://www.optisport.nl/zwembad-dordrecht"),
 ("opti-aatdejonge","Zwembad Aat de Jonge","Dronten","Flevoland","https://www.optisport.nl/zwembad-aat-de-jonge-dronten"),
 ("opti-albatros","Zwembad De Albatros","Eersel","Noord-Brabant","https://www.optisport.nl/zwembad-de-albatros-eersel"),
 ("opti-glanerbrook","Zwembad Glanerbrook","Geleen","Limburg","https://www.optisport.nl/zwembad-glanerbrook"),
 ("opti-blauwkapel","Zwembad Blauwkapel","Groenekan","Utrecht","https://www.optisport.nl/zwembad-blauwkapel-groenekan"),
 ("opti-sag","Swimming Academy Groningen","Groningen","Groningen","https://www.optisport.nl/zwembad-swimming-academy-groningen"),
 ("opti-mosaqua","Zwembad Mosaqua","Gulpen","Limburg","https://www.optisport.nl/zwembad-mosaqua"),
 ("opti-wilder","Zwembad De Wilder","Haaksbergen","Overijssel","https://www.optisport.nl/zwembad-de-wilder-haaksbergen"),
 ("opti-derdehaad","Zwembad 't Derde Haad","Harlingen","Friesland","https://www.optisport.nl/zwembad-t-derde-haad-harlingen"),
 ("opti-braak","Zwembad De Braak","Helmond","Noord-Brabant","https://www.optisport.nl/zwembad-de-braak-helmond"),
 ("opti-waterhoorn","Zwembad De Waterhoorn","Hoorn","Noord-Holland","https://www.optisport.nl/zwembad-de-waterhoorn-hoorn"),
 ("opti-wetering","Zwembad De Wetering","Houten","Utrecht","https://www.optisport.nl/zwembad-de-wetering"),
 ("opti-jottem","Zwembad Jottem","Huissen","Gelderland","https://www.optisport.nl/zwembad-jottem-huissen"),
 ("opti-steur","Zwembad De Steur","Kampen","Overijssel","https://www.optisport.nl/zwembad-de-steur-kampen"),
 ("opti-bloesem","Zwembad De Bloesem","Kapelle","Zeeland","https://www.optisport.nl/zwembad-de-bloesem-kapelle"),
 ("opti-vie","Zwembad Vie","Kerkrade","Limburg","https://www.optisport.nl/zwembad-vie-kerkrade"),
 ("opti-niervaert","Zwembad De Niervaert","Klundert","Noord-Brabant","https://www.optisport.nl/zwembad-de-niervaert-klundert"),
 ("opti-lansingh","Zwembad de Lansingh","Krimpen a/d IJssel","Zuid-Holland","https://www.optisport.nl/zwembad-de-lansingh"),
 ("opti-veenweidebad","Zwembad Veenweidebad","Mijdrecht","Utrecht","https://www.optisport.nl/zwembad-veenweidebad-mijdrecht"),
 ("opti-hogebomen","Zwembad De Hoge Bomen","Naaldwijk","Zuid-Holland","https://www.optisport.nl/zwembad-de-hoge-bomen-naaldwijk"),
 ("opti-spilbroek","Zwembad 't Spilbroek","Neede","Gelderland","https://www.optisport.nl/zwembad-t-spilbroek-neede"),
 ("opti-jvdkrol","Jaap van der Krol Bad","Nijkerkerveen","Gelderland","https://www.optisport.nl/zwembad-jaap-van-der-krol-bad-nijkerkerveen"),
 ("opti-poelmeer","Zwembad Poelmeer","Oegstgeest","Zuid-Holland","https://www.optisport.nl/zwembad-poelmeer-oegstgeest"),
 ("opti-dendonk","Zwembad Den Donk","Oisterwijk","Noord-Brabant","https://www.optisport.nl/zwembad-den-donk-oisterwijk"),
 ("opti-doelum","Zwembad Doelum","Renkum","Gelderland","https://www.optisport.nl/zwembad-doelum-renkum"),
 ("opti-denbutter","Zwembad Den Butter","Rijen","Noord-Brabant","https://www.optisport.nl/zwembad-den-butter-rijen"),
 ("opti-schilp","Zwembad De Schilp","Rijswijk","Zuid-Holland","https://www.optisport.nl/zwembad-de-schilp-rijswijk"),
 ("opti-alexanderhof","Zwembad Het Alexanderhof","Rotterdam","Zuid-Holland","https://www.optisport.nl/zwembad-het-alexanderhof-rotterdam"),
 ("opti-lockhorst","Bronbad De Lockhorst","Sliedrecht","Zuid-Holland","https://www.optisport.nl/bronbad-de-lockhorst-sliedrecht"),
 ("opti-itrak","Zwembad It Rak","Sneek","Friesland","https://www.optisport.nl/zwem-en-recreatiebad-it-rak-sneek"),
 ("opti-engh","Zwembad De Engh","Soest","Utrecht","https://www.optisport.nl/zwembad-de-engh-soest"),
 ("opti-pagedal","Zwembad Pagedal","Stadskanaal","Groningen","https://www.optisport.nl/zwembad-pagedal-stadskanaal"),
 ("opti-waalslag","Zwembad Waalslag","Tiel","Gelderland","https://www.optisport.nl/zwembad-waalslag-tiel"),
 ("opti-vanpallandt","Zwembad Van Pallandt","Varsseveld","Gelderland","https://www.optisport.nl/zwembad-van-pallandt-varsseveld"),
 ("opti-heuvelrand","Zwembad De Heuvelrand","Voorthuizen","Gelderland","https://www.optisport.nl/zwembad-de-heuvelrand-voorthuizen"),
 ("opti-watergeus","Zwembad De Watergeus","Zoetermeer","Zuid-Holland","https://www.optisport.nl/zwembad-de-watergeus-zoetermeer"),
 ("opti-zuidhorn","Zwemcentrum Zuidhorn","Zuidhorn","Groningen","https://www.optisport.nl/zwemcentrum-zuidhorn"),
 ("opti-wildert","Zwembad De Wildert","Zundert","Noord-Brabant","https://www.optisport.nl/zwembad-de-wildert-zundert"),
 ("opti-vrolijkheid","Zwembad De Vrolijkheid","Zwolle","Overijssel","https://www.optisport.nl/zwembad-de-vrolijkheid"),
 ("opti-maesemunde","Zwembad Maesemunde","'s-Gravenzande","Zuid-Holland","https://www.optisport.nl/zwembad-maesemunde"),
]
